trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    # unrelated pipelines
    - .github/*
    - .azure_pipelines/performance_check/*
    - .azure_pipelines/performance.yaml
    - .azure_pipelines/job_templates/olive-performance-template.yaml
    # commonly updated examples with no test
    - examples/directml/llama_v2/*
    - examples/directml/stable_diffusion_xl/*
    - examples/llama2/*
    - examples/open_llama/*
    - examples/stable_diffusion/*
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    # unrelated pipelines
    - .github/*
    - .azure_pipelines/performance_check/*
    - .azure_pipelines/performance.yaml
    - .azure_pipelines/job_templates/olive-performance-template.yaml
    # commonly updated examples with no test
    - examples/directml/llama_v2/*
    - examples/directml/stable_diffusion_xl/*
    - examples/llama2/*
    - examples/open_llama/*
    - examples/stable_diffusion/*

variables:
    ComponentDetection.Timeout: 2400

jobs:

# # Windows examples test
- template: job_templates/olive-example-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    onnxruntime: onnxruntime
    examples:
      inception_snpe_toolkit:
        exampleFolder: inception
        exampleName: snpe_toolkit
